# data types in python

In [1]:
str = "I HAVE LEARNED PYTHON FROM ODIN SCHOOL"

In [2]:
str_lower = str.lower()
str_lower

'i have learned python from odin school'

In [3]:
str_lower

'i have learned python from odin school'

In [4]:
str_lower.upper()

'I HAVE LEARNED PYTHON FROM ODIN SCHOOL'

In [5]:
max(str)

'Y'

In [8]:
min(str)

' '

In [9]:
# tuple

tuple1 = (1,2,3,4,5)
tuple2 = (6,7,8,9)

tuple1+=tuple2  # tuple1 + tuple2

print(tuple1)

(1, 2, 3, 4, 5, 6, 7, 8, 9)


In [10]:
tuple1

(1, 2, 3, 4, 5, 6, 7, 8, 9)

In [11]:
tuple1*2

(1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9)

In [12]:
tuple

tuple

In [13]:
tuple1

(1, 2, 3, 4, 5, 6, 7, 8, 9)

In [15]:
tuple1[3]

4

In [16]:
tuple1[4:6]

(5, 6)

In [17]:
list1 = [4,5,6]
list2 = [7,8,9]

list1+=list2

print(list1)

[4, 5, 6, 7, 8, 9]


In [18]:
list1

[4, 5, 6, 7, 8, 9]

In [19]:
list1[1:3]

[5, 6]

In [20]:
list1 += ["f"] # trick to add 

In [21]:
list1

[4, 5, 6, 7, 8, 9, 'f']

In [29]:
list1.append(["i","c"])  # in append if we add two elements then it shows in another bracket

In [30]:
list1

[4, 5, 6, 7, 8, 9, 'f', 'i', 'p', 'i', ['i', 'c']]

In [32]:
list1.extend(["p","m"])  # extend show the list in one 

In [33]:
list1

[4, 5, 6, 7, 8, 9, 'f', 'i', 'p', 'i', ['i', 'c'], 'p', 'm']

In [34]:
list1

[4, 5, 6, 7, 8, 9, 'f', 'i', 'p', 'i', ['i', 'c'], 'p', 'm']

In [36]:
list1.insert(2,"h")

In [37]:
list1

[4, 5, 'h', 6, 7, 8, 9, 'f', 'i', 'p', 'i', ['i', 'c'], 'p', 'm']

In [38]:
dict = {}

In [39]:
print(dict)

{}


In [41]:
dict1 = {1:"string1", 2:"strig2", 3:"string3"}

print(dict1)

{1: 'string1', 2: 'strig2', 3: 'string3'}


In [43]:
dict1.keys()

dict_keys([1, 2, 3])

In [45]:
len(dict1)

3

In [46]:
dict1.values()

dict_values(['string1', 'strig2', 'string3'])

In [51]:
set = {"a","b","c","d"}
set1 = {"e","b","g","h"}

set | set1  # union

{'a', 'b', 'c', 'd', 'e', 'g', 'h'}

In [53]:
set & set1 # intersection

{'b'}

In [55]:
set - set1 # diiference

{'a', 'c', 'd'}

In [56]:
set.difference(set1)

{'a', 'c', 'd'}

# python function call

In [11]:
a=10
def changeit(b):
    print("value of b is",b)
    b=100
    print("value of new b is",b)
changeit(a)

value of b is 10
value of new b is 100


In [12]:
c=[10,20,30]
def changethem(d):
    print("value of d is",d)
    d[0]=99
    d[1]=96
    print("ne value of d is",d)
changethem(c)

value of d is [10, 20, 30]
ne value of d is [99, 96, 30]


In [13]:
a=20
def changeif(m):
    print("value of m is",m)
    m=200
    print("value of new m is",m)
changeif(a)

value of m is 20
value of new m is 200


In [14]:
z=[100,200,300,500]
def change(k):
    print("value of k is",k)
    k[0]=900
    k[3]=1000
    print("value of new k is",k)
change(z)

value of k is [100, 200, 300, 500]
value of new k is [900, 200, 300, 1000]


In [16]:
def my_function(fname,lname):
    print(f'first name is {fname} and last name is {lname}')

In [18]:
my_function("abhishek","bhambak")

first name is abhishek and last name is bhambak


In [21]:
class student:
    __init__(self,name,last,clas):
        self.name=name
        self.last=last
        self.clas=clas
    def participated(self):
        print("yes! they are well qualified student")
h=student()

SyntaxError: invalid syntax (<ipython-input-21-586e2d0f1812>, line 2)

In [22]:
def my_functions():
    d=10
    d+=1
    print(d)

In [24]:
fruits=["apple","mango","banana","cherry","dragon fruit"]
if "mango" in fruits:
    print (3+3)
else:
    print (2*2)

6


# lambda

In [25]:
x=lambda a: a+10
print(x(5))

15


In [26]:
y=lambda a: a*2
print(y(4))

8


In [27]:
def multiply(x,y):
    print (x+y)

In [29]:
multiply(3,7)

10


In [31]:
r=lambda x,y: x+y
r(2,3)

5

In [32]:
r(12,12)

24

In [33]:
def myfunc(n):
    return lambda a: a+n

mysum=myfunc(3)
print(mysum(10))

13


In [34]:
def my_function(x):
    return lambda a: a+x

myval=my_function(5)
print(myval(20))

25


In [36]:
g=lambda a,b,c: a+b+c
print(g(1,2,3))

6


In [1]:
def my_func(n):
    return lambda a: a*n
double=my_func(2)
print(double(11))

22


# creating array

In [2]:
import numpy as np

In [13]:
a=np.array([1,2,3])
b=np.array((1,2,3))
print(a)
print(b)

[1 2 3]
[1 2 3]


In [15]:
c=np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [17]:
c.shape

(2, 3)

In [18]:
c[0]

array([1, 2, 3])

In [19]:
c[1]

array([4, 5, 6])

In [20]:
c[:1]

array([[1, 2, 3]])

In [21]:
type(a)

numpy.ndarray

In [22]:
c[1:]

array([[4, 5, 6]])

In [26]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [30]:
np.arange(10,25,5)

array([10, 15, 20])

In [31]:
np.arange(5,10,3)

array([5, 8])

In [32]:
np.linspace(5,10,10)

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

In [33]:
np.full((2,2),6)

array([[6, 6],
       [6, 6]])

In [34]:
np.full((5,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [35]:
np.random.random((3,3))

array([[0.62394223, 0.28509623, 0.77430792],
       [0.55113364, 0.19271613, 0.04498175],
       [0.63825396, 0.64170176, 0.60801982]])

In [41]:
k=np.random.randint((3,3))
print(k)

[1 1]


In [42]:
w=np.array([[1,2,3,4],[0,9,8,7]])
print(w)

[[1 2 3 4]
 [0 9 8 7]]


In [43]:
w.shape

(2, 4)

In [47]:
w.shape=(4,2)
w.shape[0]

4

In [48]:
w

array([[1, 2],
       [3, 4],
       [0, 9],
       [8, 7]])

In [49]:
w.shape=(2,4)
w.shape[1]

4

In [50]:
w

array([[1, 2, 3, 4],
       [0, 9, 8, 7]])

In [51]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [52]:
w.size

8

In [53]:
w.ndim

2

In [54]:
a

array([1, 2, 3])

In [55]:
b

array([1, 2, 3])

In [58]:
a.dtype

dtype('int32')

In [59]:
b.dtype

dtype('int32')